feat: add header
Ananasovna/todo-project pull request #4
Opened 2022-10-10 14:27 UTC by Ananasovna

Add header

2022-10-10 22:03 UTC, mishashmidt0 requested changes
Крч инкапсулируй иконки и продолжай

2022-10-10 22:03 UTC, mishashmidt0 commented on src/components/Header/User/User.tsx
> +              <path d="M19.5 0C8.736 0 0 8.736 0 19.5C0 30.264 8.736 39 19.5 39C30.264 39 39 30.264 39 19.5C39 8.736 30.264 0 19.5 0ZM19.5 5.85C22.737 5.85 25.35 8.463 25.35 11.7C25.35 14.937 22.737
для удобста, лучше отдельно создать папку для иконок и в виде компонент в tsx  и сохранять

2022-10-10 22:03 UTC, mishashmidt0 commented on src/components/Header/Search/Search.tsx
> +                <path d="M19.0815 16.8077C20.6549 14.6604 21.3596 11.998 21.0547 9.35332C20.7497 6.70862 19.4575 4.27661 17.4367 2.54384C15.4158 0.81107 12.8153 -0.0946645 10.1554 0.00783994C7.49555
ниже коммент по этому поводу

2022-10-11 14:13 UTC, Ananasovna commented on src/components/Header/User/User.tsx
> +              <path d="M19.5 0C8.736 0 0 8.736 0 19.5C0 30.264 8.736 39 19.5 39C30.264 39 39 30.264 39 19.5C39 8.736 30.264 0 19.5 0ZM19.5 5.85C22.737 5.85 25.35 8.463 25.35 11.7C25.35 14.937 22.737
сделано

2022-10-11 14:13 UTC, Ananasovna commented on src/components/Header/Search/Search.tsx
> +                <path d="M19.0815 16.8077C20.6549 14.6604 21.3596 11.998 21.0547 9.35332C20.7497 6.70862 19.4575 4.27661 17.4367 2.54384C15.4158 0.81107 12.8153 -0.0946645 10.1554 0.00783994C7.49555
сделано

2022-10-12 20:37 UTC, merged